'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, ArrowRight, Bot, CheckCircle, Info, Plus, X } from 'lucide-react';
import { Topbar } from '@/components/layout/topbar';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { DEMO_SUPPLIERS } from '@/lib/demo-data';
import { formatCurrency } from '@/lib/utils';
import { toast } from 'sonner';
import type { Supplier } from '@/types';

const STEPS = ['Basic Info', 'Specifications & SOW', 'Review & Strategy', 'Invite Suppliers'];

const SA_PROVINCES = [
  { value: 'GP', label: 'Gauteng' },
  { value: 'WC', label: 'Western Cape' },
  { value: 'KZN', label: 'KwaZulu-Natal' },
  { value: 'EC', label: 'Eastern Cape' },
  { value: 'FS', label: 'Free State' },
  { value: 'LP', label: 'Limpopo' },
  { value: 'MP', label: 'Mpumalanga' },
  { value: 'NC', label: 'Northern Cape' },
  { value: 'NW', label: 'North West' },
];

const CATEGORIES = [
  { value: 'it_equipment', label: 'IT Equipment' },
  { value: 'office_supplies', label: 'Office Supplies' },
  { value: 'construction', label: 'Construction' },
  { value: 'professional_services', label: 'Professional Services' },
  { value: 'facilities', label: 'Facilities' },
  { value: 'logistics', label: 'Logistics' },
  { value: 'security', label: 'Security' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'other', label: 'Other' },
];

const BBBEE_OPTIONS = [
  { value: 'level_1_2', label: 'Level 1–2 only (preferred)' },
  { value: 'level_1_4', label: 'Level 1–4' },
  { value: 'level_1_6', label: 'Level 1–6' },
  { value: 'any', label: 'Any level' },
  { value: 'none', label: 'Not required' },
];

interface FormData {
  title: string;
  category: string;
  type: string;
  budget: string;
  delivery_location: string;
  delivery_province: string;
  required_by: string;
  bbbee_requirement: string;
  min_quotes: string;
  specifications: string;
  sow: string;
}

function getPFMARecommendation(budget: number): { type: string; label: string; color: string; description: string } {
  if (budget < 30_000) {
    return { type: 'Petty Cash / Direct Award', label: 'Under R30,000', color: 'bg-green-50 border-green-200 text-green-800', description: 'Budget is below the petty cash threshold. Direct award is permitted with one quote.' };
  }
  if (budget <= 500_000) {
    return { type: 'Three-Quote Process (RFQ)', label: 'R30,000 – R500,000', color: 'bg-blue-50 border-blue-200 text-blue-800', description: 'PFMA requires a minimum of three written quotations. Use the RFQ process.' };
  }
  return { type: 'Open Tender', label: 'Over R500,000', color: 'bg-amber-50 border-amber-200 text-amber-800', description: 'Budget exceeds R500,000. An open competitive tender advertised on the eTender Portal is required by PFMA.' };
}

export default function NewProcurementPage() {
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [isGeneratingSow, setIsGeneratingSow] = useState(false);
  const [selectedSuppliers, setSelectedSuppliers] = useState<Set<string>>(new Set());
  const [form, setForm] = useState<FormData>({
    title: '',
    category: '',
    type: '',
    budget: '',
    delivery_location: '',
    delivery_province: '',
    required_by: '',
    bbbee_requirement: '',
    min_quotes: '3',
    specifications: '',
    sow: '',
  });

  function update(field: keyof FormData, value: string) {
    setForm((prev) => ({ ...prev, [field]: value }));
  }

  async function handleGenerateSow() {
    if (!form.title || !form.category) {
      toast.error('Please fill in title and category first.');
      return;
    }
    setIsGeneratingSow(true);
    try {
      const res = await fetch('/api/ai', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ mode: 'sow', title: form.title, category: form.category, specifications: form.specifications }),
      });
      if (res.ok) {
        const data = await res.json();
        update('sow', data.content ?? data.sow ?? 'SOW generated successfully.');
        toast.success('Scope of Work generated by AI');
      } else {
        throw new Error('API error');
      }
    } catch {
      // Fallback demo SOW
      update('sow', `SCOPE OF WORK\n\n1. BACKGROUND\nThis procurement is for ${form.title}. The organisation requires this supply/service to meet operational requirements.\n\n2. OBJECTIVES\nThe primary objective is to procure ${form.title} that meets the technical specifications outlined herein.\n\n3. SCOPE OF SUPPLY\n- Supply and delivery of goods/services as specified\n- Compliance with all relevant South African standards\n- Warranty/guarantee as per RFQ requirements\n\n4. DELIVERY REQUIREMENTS\nDelivery to: ${form.delivery_location || '[Delivery Address]'}\nRequired by: ${form.required_by || '[Required Date]'}\n\n5. EVALUATION CRITERIA\nBids will be evaluated on the PPPFA 90/10 principle:\n- Price: 40 points\n- BBBEE Status: 20 points\n- Technical Compliance: 20 points\n- Delivery Schedule: 20 points\n\n6. COMPLIANCE REQUIREMENTS\n- Valid SARS Tax Clearance Certificate\n- BBBEE Certificate (${form.bbbee_requirement || 'as specified'})\n- CIPC Company Registration\n- Proof of bank account`);
      toast.success('SOW generated (demo mode)');
    } finally {
      setIsGeneratingSow(false);
    }
  }

  function toggleSupplier(id: string) {
    setSelectedSuppliers((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function handleSendRFQ() {
    if (selectedSuppliers.size === 0) {
      toast.error('Please select at least one supplier.');
      return;
    }
    toast.success(`RFQ sent to ${selectedSuppliers.size} supplier(s)! Reference: RFQ/PT/2025/051`);
    setTimeout(() => router.push('/procurements'), 1500);
  }

  const budget = parseFloat(form.budget) || 0;
  const pfma = getPFMARecommendation(budget);

  // Filterable suppliers for step 4
  const [supplierSearch, setSupplierSearch] = useState('');
  const filteredSuppliers = DEMO_SUPPLIERS.filter((s) =>
    !supplierSearch || s.company_name.toLowerCase().includes(supplierSearch.toLowerCase())
  );

  return (
    <div className="flex flex-col h-full">
      <Topbar
        title="New Procurement"
        subtitle="CIPS-compliant procurement wizard"
        actions={
          <Button variant="outline" size="sm" className="h-8 text-xs gap-1.5" onClick={() => router.push('/procurements')}>
            <ArrowLeft className="w-3.5 h-3.5" />
            Cancel
          </Button>
        }
      />

      <div className="flex-1 overflow-auto p-6">
        <div className="max-w-3xl mx-auto space-y-6">
          {/* Step indicator */}
          <div className="flex items-center gap-0">
            {STEPS.map((label, idx) => {
              const isCompleted = idx < step;
              const isCurrent = idx === step;
              return (
                <div key={idx} className="flex items-center flex-1">
                  <div className="flex flex-col items-center gap-1">
                    <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold transition-all ${
                      isCompleted ? 'bg-green-500 text-white' :
                      isCurrent ? 'bg-[var(--brand-blue)] text-white' :
                      'bg-gray-100 text-gray-400'
                    }`}>
                      {isCompleted ? <CheckCircle className="w-5 h-5" /> : idx + 1}
                    </div>
                    <span className={`text-xs whitespace-nowrap ${isCurrent ? 'text-[var(--brand-blue)] font-semibold' : 'text-[var(--text-tertiary)]'}`}>
                      {label}
                    </span>
                  </div>
                  {idx < STEPS.length - 1 && (
                    <div className={`h-0.5 flex-1 mx-2 mt-[-16px] ${idx < step ? 'bg-green-400' : 'bg-gray-200'}`} />
                  )}
                </div>
              );
            })}
          </div>

          {/* Step 1: Basic Info */}
          {step === 0 && (
            <div className="bg-white border border-[var(--border-default)] rounded-xl shadow-sm p-6 space-y-5">
              <h2 className="text-base font-semibold text-[var(--text-primary)]">Step 1: Basic Information</h2>

              <div className="space-y-2">
                <Label htmlFor="title">Procurement Title <span className="text-red-500">*</span></Label>
                <Input id="title" placeholder="e.g. 500× Laptop Computers" value={form.title} onChange={(e) => update('title', e.target.value)} />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Category <span className="text-red-500">*</span></Label>
                  <Select value={form.category} onValueChange={(v) => { if (v) update('category', v); }}>
                    <SelectTrigger><SelectValue placeholder="Select category" /></SelectTrigger>
                    <SelectContent>
                      {CATEGORIES.map((c) => <SelectItem key={c.value} value={c.value}>{c.label}</SelectItem>)}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Procurement Type <span className="text-red-500">*</span></Label>
                  <Select value={form.type} onValueChange={(v) => { if (v) update('type', v); }}>
                    <SelectTrigger><SelectValue placeholder="Select type" /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="rfq">RFQ (Request for Quotation)</SelectItem>
                      <SelectItem value="rfp">RFP (Request for Proposal)</SelectItem>
                      <SelectItem value="tender">Open Tender</SelectItem>
                      <SelectItem value="sole_source">Sole Source</SelectItem>
                      <SelectItem value="emergency">Emergency Procurement</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="budget">Budget (ZAR) <span className="text-red-500">*</span></Label>
                  <Input id="budget" type="number" placeholder="0" value={form.budget} onChange={(e) => update('budget', e.target.value)} />
                  {budget > 0 && (
                    <p className="text-xs text-[var(--text-tertiary)]">= {formatCurrency(budget)}</p>
                  )}
                </div>
                <div className="space-y-2">
                  <Label htmlFor="min_quotes">Minimum Quotes Required</Label>
                  <Input id="min_quotes" type="number" min="1" max="10" value={form.min_quotes} onChange={(e) => update('min_quotes', e.target.value)} />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="delivery_location">Delivery Location <span className="text-red-500">*</span></Label>
                <Input id="delivery_location" placeholder="e.g. Johannesburg CBD" value={form.delivery_location} onChange={(e) => update('delivery_location', e.target.value)} />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Delivery Province <span className="text-red-500">*</span></Label>
                  <Select value={form.delivery_province} onValueChange={(v) => { if (v) update('delivery_province', v); }}>
                    <SelectTrigger><SelectValue placeholder="Select province" /></SelectTrigger>
                    <SelectContent>
                      {SA_PROVINCES.map((p) => <SelectItem key={p.value} value={p.value}>{p.label}</SelectItem>)}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="required_by">Required By Date <span className="text-red-500">*</span></Label>
                  <Input id="required_by" type="date" value={form.required_by} onChange={(e) => update('required_by', e.target.value)} />
                </div>
              </div>

              <div className="space-y-2">
                <Label>BBBEE Requirement</Label>
                <Select value={form.bbbee_requirement} onValueChange={(v) => { if (v) update('bbbee_requirement', v); }}>
                  <SelectTrigger><SelectValue placeholder="Select BBBEE requirement" /></SelectTrigger>
                  <SelectContent>
                    {BBBEE_OPTIONS.map((o) => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
            </div>
          )}

          {/* Step 2: Specifications & SOW */}
          {step === 1 && (
            <div className="space-y-4">
              <div className="bg-white border border-[var(--border-default)] rounded-xl shadow-sm p-6 space-y-4">
                <h2 className="text-base font-semibold text-[var(--text-primary)]">Step 2: Specifications & Scope of Work</h2>

                <div className="space-y-2">
                  <Label htmlFor="specs">Technical Specifications & Requirements</Label>
                  <Textarea
                    id="specs"
                    placeholder="Describe the technical requirements, quantities, standards, quality requirements..."
                    className="min-h-[120px] resize-none"
                    value={form.specifications}
                    onChange={(e) => update('specifications', e.target.value)}
                  />
                </div>

                <Button
                  onClick={handleGenerateSow}
                  disabled={isGeneratingSow}
                  className="bg-[var(--brand-blue)] text-white hover:bg-blue-700 gap-2"
                >
                  <Bot className="w-4 h-4" />
                  {isGeneratingSow ? 'Generating SOW...' : 'Generate SOW with AI'}
                </Button>
              </div>

              {form.sow && (
                <div className="bg-white border border-blue-200 rounded-xl shadow-sm p-6 space-y-3">
                  <div className="flex items-center gap-2">
                    <Bot className="w-4 h-4 text-[var(--brand-blue)]" />
                    <h3 className="text-sm font-semibold text-[var(--brand-blue)]">AI-Generated Scope of Work</h3>
                    <Badge variant="outline" className="text-xs ml-auto">Editable</Badge>
                  </div>
                  <Textarea
                    value={form.sow}
                    onChange={(e) => update('sow', e.target.value)}
                    className="min-h-[300px] font-mono text-xs resize-none"
                  />
                </div>
              )}

              {/* Market Intelligence box */}
              <div className="bg-amber-50 border border-amber-200 rounded-xl p-5">
                <div className="flex items-start gap-3">
                  <Info className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
                  <div>
                    <h3 className="text-sm font-semibold text-amber-800 mb-1">AI Market Intelligence</h3>
                    <p className="text-sm text-amber-700 mb-3">
                      Based on category <strong>{form.category || 'selected'}</strong>, AI suggests the following price benchmarks:
                    </p>
                    <div className="grid grid-cols-3 gap-4">
                      <div className="bg-white rounded-lg p-3 text-center border border-amber-200">
                        <p className="text-xs text-amber-600">Market Low</p>
                        <p className="font-bold text-amber-900">{budget > 0 ? formatCurrency(budget * 0.82) : 'R–'}</p>
                      </div>
                      <div className="bg-white rounded-lg p-3 text-center border border-amber-200">
                        <p className="text-xs text-amber-600">Market Median</p>
                        <p className="font-bold text-amber-900">{budget > 0 ? formatCurrency(budget * 0.95) : 'R–'}</p>
                      </div>
                      <div className="bg-white rounded-lg p-3 text-center border border-amber-200">
                        <p className="text-xs text-amber-600">Market High</p>
                        <p className="font-bold text-amber-900">{budget > 0 ? formatCurrency(budget * 1.12) : 'R–'}</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Step 3: Review & Strategy */}
          {step === 2 && (
            <div className="space-y-4">
              <div className="bg-white border border-[var(--border-default)] rounded-xl shadow-sm p-6">
                <h2 className="text-base font-semibold text-[var(--text-primary)] mb-4">Step 3: Review & Procurement Strategy</h2>

                <div className="space-y-3">
                  <div className="grid grid-cols-2 gap-x-6 gap-y-3">
                    <div>
                      <p className="text-xs text-[var(--text-tertiary)]">Title</p>
                      <p className="text-sm font-medium text-[var(--text-primary)]">{form.title || '—'}</p>
                    </div>
                    <div>
                      <p className="text-xs text-[var(--text-tertiary)]">Category</p>
                      <p className="text-sm font-medium text-[var(--text-primary)]">
                        {CATEGORIES.find((c) => c.value === form.category)?.label || '—'}
                      </p>
                    </div>
                    <div>
                      <p className="text-xs text-[var(--text-tertiary)]">Type</p>
                      <p className="text-sm font-medium text-[var(--text-primary)]">{form.type?.toUpperCase() || '—'}</p>
                    </div>
                    <div>
                      <p className="text-xs text-[var(--text-tertiary)]">Budget</p>
                      <p className="text-sm font-medium text-[var(--text-primary)]">{budget > 0 ? formatCurrency(budget) : '—'}</p>
                    </div>
                    <div>
                      <p className="text-xs text-[var(--text-tertiary)]">Delivery Location</p>
                      <p className="text-sm font-medium text-[var(--text-primary)]">{form.delivery_location || '—'}</p>
                    </div>
                    <div>
                      <p className="text-xs text-[var(--text-tertiary)]">Province</p>
                      <p className="text-sm font-medium text-[var(--text-primary)]">
                        {SA_PROVINCES.find((p) => p.value === form.delivery_province)?.label || '—'}
                      </p>
                    </div>
                    <div>
                      <p className="text-xs text-[var(--text-tertiary)]">Required By</p>
                      <p className="text-sm font-medium text-[var(--text-primary)]">{form.required_by || '—'}</p>
                    </div>
                    <div>
                      <p className="text-xs text-[var(--text-tertiary)]">BBBEE Requirement</p>
                      <p className="text-sm font-medium text-[var(--text-primary)]">
                        {BBBEE_OPTIONS.find((o) => o.value === form.bbbee_requirement)?.label || '—'}
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              {/* PFMA Threshold */}
              {budget > 0 && (
                <div className={`border rounded-xl p-5 ${pfma.color}`}>
                  <div className="flex items-start gap-3">
                    <Info className="w-5 h-5 shrink-0 mt-0.5" />
                    <div>
                      <div className="flex items-center gap-2 mb-1">
                        <h3 className="text-sm font-semibold">Recommended Strategy: {pfma.type}</h3>
                        <Badge variant="outline" className="text-xs">{pfma.label}</Badge>
                      </div>
                      <p className="text-sm leading-relaxed">{pfma.description}</p>
                    </div>
                  </div>
                </div>
              )}

              {/* SOW Preview */}
              {form.sow && (
                <div className="bg-white border border-[var(--border-default)] rounded-xl shadow-sm p-5">
                  <h3 className="text-sm font-semibold text-[var(--text-primary)] mb-2">Scope of Work Preview</h3>
                  <pre className="text-xs text-[var(--text-secondary)] whitespace-pre-wrap font-mono leading-relaxed max-h-48 overflow-y-auto">
                    {form.sow}
                  </pre>
                </div>
              )}
            </div>
          )}

          {/* Step 4: Invite Suppliers */}
          {step === 3 && (
            <div className="space-y-4">
              <div className="bg-white border border-[var(--border-default)] rounded-xl shadow-sm p-6">
                <div className="flex items-center justify-between mb-4">
                  <div>
                    <h2 className="text-base font-semibold text-[var(--text-primary)]">Step 4: Invite Suppliers</h2>
                    <p className="text-sm text-[var(--text-secondary)] mt-0.5">
                      {selectedSuppliers.size} supplier(s) selected
                    </p>
                  </div>
                  <Input
                    placeholder="Search suppliers..."
                    value={supplierSearch}
                    onChange={(e) => setSupplierSearch(e.target.value)}
                    className="w-56 h-8 text-sm"
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  {filteredSuppliers.map((supplier: Supplier) => {
                    const isSelected = selectedSuppliers.has(supplier.id);
                    const bbbeeColors: Record<number, string> = { 1: 'bg-green-100 text-green-800', 2: 'bg-green-100 text-green-800', 3: 'bg-amber-100 text-amber-800', 4: 'bg-amber-100 text-amber-800' };
                    const bbbeeColor = supplier.bbbee_level ? (bbbeeColors[supplier.bbbee_level] ?? 'bg-red-100 text-red-800') : 'bg-gray-100 text-gray-600';
                    return (
                      <button
                        key={supplier.id}
                        onClick={() => toggleSupplier(supplier.id)}
                        className={`text-left p-4 rounded-lg border-2 transition-all ${
                          isSelected
                            ? 'border-[var(--brand-blue)] bg-blue-50'
                            : 'border-[var(--border-default)] bg-white hover:border-blue-300'
                        }`}
                      >
                        <div className="flex items-start justify-between gap-2 mb-2">
                          <p className="text-sm font-semibold text-[var(--text-primary)] leading-tight">{supplier.company_name}</p>
                          {isSelected && <CheckCircle className="w-4 h-4 text-[var(--brand-blue)] shrink-0" />}
                        </div>
                        <div className="flex items-center gap-2 flex-wrap">
                          {supplier.bbbee_level && (
                            <span className={`text-xs px-1.5 py-0.5 rounded font-medium ${bbbeeColor}`}>
                              BBBEE L{supplier.bbbee_level}
                            </span>
                          )}
                          <span className={`text-xs px-1.5 py-0.5 rounded font-medium ${
                            supplier.status === 'approved' ? 'bg-green-100 text-green-800' : 'bg-amber-100 text-amber-800'
                          }`}>
                            {supplier.status}
                          </span>
                          <span className="text-xs text-[var(--text-tertiary)]">{supplier.province}</span>
                        </div>
                        <p className="text-xs text-[var(--text-tertiary)] mt-1.5">
                          Grade: {supplier.grade?.grade ?? '–'} · {supplier.response_rate}% response rate
                        </p>
                      </button>
                    );
                  })}
                </div>
              </div>

              <Button
                onClick={handleSendRFQ}
                className="w-full bg-[var(--brand-blue)] text-white hover:bg-blue-700 h-11 text-sm font-semibold gap-2"
              >
                <Plus className="w-4 h-4" />
                Send RFQ to {selectedSuppliers.size > 0 ? `${selectedSuppliers.size} Supplier(s)` : 'Selected Suppliers'}
              </Button>
            </div>
          )}

          {/* Navigation */}
          <div className="flex items-center justify-between pt-2">
            <Button
              variant="outline"
              onClick={() => step > 0 ? setStep(step - 1) : router.push('/procurements')}
              className="gap-2"
            >
              <ArrowLeft className="w-4 h-4" />
              {step === 0 ? 'Cancel' : 'Back'}
            </Button>

            {step < STEPS.length - 1 && (
              <Button
                onClick={() => setStep(step + 1)}
                className="bg-[var(--brand-blue)] text-white hover:bg-blue-700 gap-2"
              >
                Next
                <ArrowRight className="w-4 h-4" />
              </Button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
